---
title: "My Report"
author: "Cathy"
format: html
editor: visual
date: Jul-2025
categories: [R, 25Winter, "data: books.csv"]
---

## Books dataset with Quarto

Investigating the books dataset within quarto

## Loading the required packages


```{r}
library(ggplot2)
library(dplyr)
```

## Loading the packages

```{r}
books <-  read.csv("../../../../data/books.csv")
```

## The books dataset includes the following fields

```{r}
names(books)
```

## This graph shows the the volume of publications by language code

```{r}
books |> 
  ggplot(mapping = aes(x = language_code)) +
  geom_bar()
```

## Due to the large number of english language books, We will create a data subset without the codes 'eng' and 'en-US'.

```{r}
non_english_books <- filter(books,!language_code %in% c("en-US","eng"))
non_english_books |> 
  ggplot(mapping = aes(x = language_code)) +
  geom_bar()
#| fig-cap: "Number of Non-English Books Published"
```

```{r}
ggplot(data = non_english_books,
       mapping = aes(x = num_pages,
                     y = publisher)) +
  geom_point()
```






