{
  "hash": "c02d4f1e5d6659b5eecc29293dae6765",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Striker and Height Conundrum\"\nauthor: \"Mariana, Rennie, Shuvo\"\nformat: html\neditor: visual\nexecute: \n  warning: false\ndate: Jan-2026\ncategories: [R, 26Summer, \"data: Players2024.csv\"]\n---\n\n## Introduction\n\nThis presentation is done by Rennie Lee, Mariana P. Liborio and Shuvo Marak. We primarily used dplyr, gt, ggplot2 library for the presentation. Our main goal is to debunk the popular myth of the best height for a player being attacker/striker in the Football. For this analysis we used the Soccer Players data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(gt)\nlibrary(ggplot2)\n\nplayers <- read.csv(\"../../../../data/Players2024.csv\")\n\nplayers <- players %>% mutate(striker=if_else(positions==\"Attack\",1,0))\n```\n:::\n\n\nMost strikers comes from Spain, followed by France, Ukraine, Turkey.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstriker_by_country <- players %>% \n  filter(striker==1) %>% \n  count(nationality, name=\"num_striker\") %>% \n  arrange(desc(num_striker))\nhead(striker_by_country)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  nationality num_striker\n1       Spain         112\n2      France          97\n3     Ukraine          82\n4     Türkiye          70\n5     Germany          69\n6      Russia          65\n```\n\n\n:::\n\n```{.r .cell-code}\nstriker_by_country <-\nstriker_by_country %>% slice_head(n=5) %>% \n  gt() %>% tab_header(title = md(\"**Top 5 Countries by Number of Strikers**\"),\n    subtitle = \"Players2024 Dataset\") %>%\n  cols_label(nationality = \"Country\", num_striker = \"Number of Strikers\") %>%\n  fmt_number(columns = num_striker, decimals = 0) %>%\n  tab_source_note(source_note = \"Source: Players2024.csv\")\n```\n:::\n\n\nFrom the data we found that the average height of striker is 180.80cm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeanht <- mean(players$height_cm, na.rm=TRUE)\nggplot(players, aes(x= height_cm))+ geom_histogram(bins = 10, fill=\"skyblue\", color= \"green\")+ geom_vline(xintercept = meanht, color=\"purple\", line= 20) +\nlabs(\n    title = \"Distribution of Player Heights\",\n    x = \"Height (cm)\",\n    y = \"Number of Players\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](The_Striker_-_Height_Conundrum_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe height of the strikers are tend to stick around 180cm( mean = 180.80cm)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstrikers_height <- players %>% filter(striker==1)\nstrikers_heightm <- mean(strikers_height$height_cm, na.rm = TRUE)\nggplot(strikers_height, aes(x= height_cm)) + geom_histogram(binwidth = 2, fill = \"skyblue\", color = \"black\") +\n  geom_vline(\n    xintercept = mean(strikers_height$height_cm, na.rm = TRUE),\n    color = \"red\",line = 3)+\n  labs(\n    title = \"Distribution of Strikers Heights\",\n    x = \"Height (cm)\",\n    y = \"Number of Strikers\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](The_Striker_-_Height_Conundrum_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(players$striker)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0    1 \n4364 1571 \n```\n\n\n:::\n\n```{.r .cell-code}\ncor_height_striker <- cor(\n  players$height_cm,\n  players$striker,\n  use = \"complete.obs\"\n)\ncor_height_striker\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.1752134\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(players, aes(x = factor(striker), y = height_cm)) +\n  geom_boxplot(fill = \"skyblue\", alpha = 0.7) +\n  labs(\n    title = \"Height Differences Between Strikers and Non-Strikers\",\n    x = \"Striker Status (0 = Non-Striker, 1 = Striker)\",\n    y = \"Height (cm)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](The_Striker_-_Height_Conundrum_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThere are 4364 non-striker player and 1571 strikes in our data. From analysis and from the Boxplot we see that there is a very small correlation with strikers and non-strikers height(-0.1752, which is negligible). So, we can say that there is no correlation with players height and being a striker player!\n",
    "supporting": [
      "The_Striker_-_Height_Conundrum_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}