---
title: My Python project
author: Nahar
date: 07/10/2025
format: html
warning: false
echo: false
execute:
    eval: false # Data not available, need to fix...
categories: [Python, 2025 Winter]
---



## Introduction
::: {.justify}
Dengue fever is transmitted through the wound of an 
Aedes mosquito that harbors the dengue virus. 
Transmission occurs when the mosquito acquires the 
virus from an individual with circulating dengue 
virus in their bloodstream during a biting interaction. 
Symptoms typically manifest within four to six days 
post-infection and can persist for about ten days. 
While some cases present mild symptoms that could be 
mistaken for the flu or other viral infections, the potential 
development of severe complications should not be overlooked. 
This study aims to develop a some basic descriptive analysis
capable of utilizing relevant information to show dengue 
outbreaks within the geographic regions of Bangladesh.
:::

## Dengue Cases data of Bangladesh
```{python}
import pandas as pd
df = pd.read_csv('gallery/Python/25Winter/Mst Noorunnahar/data/data_DENV.csv')
df
df.head()
```
## Viewing the data structure

```{python}
df.columns
df.info()
df.describe()
```
## Descriptive Statistics of all variables
## Total number of observations:
```{python}
dengue = df["cases"]
print("There are " + str(dengue.count()) + " cases of dengue" )
temp= df["temp_avg"]
print("There are " + str(temp.count()) + " average temperature" )
```

## Measures of central tendency
```{python}
dengue.mean()
dengue.mode()
dengue.median()
```

## Summary of statistics

```{python}
dengue.describe()
```
## Inferential Statistics
```{python}
import scipy.stats as stats
stats.linregress(x = df["temp_avg"], y = df["cases"])
lm = stats.linregress(x = df["temp_avg"], y = df["cases"])
lm.pvalue
```
## Checking relationship between variables
```{python}
import seaborn as sns
import matplotlib.pyplot as plt
sns.relplot(data = df, x = df["temp_avg"], y = df["cases"])
```






