---
title: Tips
---

Here's a few general tips. In addition, we strongly recommend using [the pandas cheatsheets](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf), which give a quick and easy reference for common packages and functions, and [from Data to Viz](https://www.data-to-viz.com/), which guides you through choosing a visualisation.

## Hotkeys

::: {.panel-tabset group="lang"}

## R {.active}

| Code | Hotkey | Description |
| --- | --- | --- |
|  | <kbd>Ctrl</kbd>+<kbd>Enter</kbd> | Run current line (when in Script) |
| `<-` | <kbd>Alt</kbd>+<kbd>-</kbd> | Assignment |
| `%>%` | <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> | Pipe |
|  | <kbd>Esc</kbd> | Cancel current operation (when in Console) |
|  | <kbd>F1</kbd> | Help documentation for selected function |

## Python

| Code | Hotkey | Description |
| --- | --- | --- |
|  | <kbd>F9</kbd> (or <kbd>Fn</kbd> + <kbd>F9</kbd>) | Run current line |
| `# %%` | <kbd>Ctrl</kbd> + <kbd>2</kbd> | New cell (only in Spyder) |
|  | <kbd>Ctrl</kbd>+<kbd>Enter</kbd> | Run current cell (when in Script) |
|  | <kbd>Ctrl</kbd>+<kbd>C</kbd> | Cancel current operation (when in Console) |
  
:::

## Interface Customisation

::: {.panel-tabset group="lang"}

## R {.active}

You can make Positron a little nicer and suited to yourself by changing its appearance, colour and using Snippets

**Appearance**

`Manage > Themes > Colour Themes`

Choose an application themes that suits your eyes.

**Snippets**

Snippets allow you to create your own code-driven shortcuts.

For example, if you type `shinyapp` into a .R file in Positron (with the Shiny extension installed), and then press the Tab key, it will add a Shiny app scaffold to your script.

You can find more Snippets, and add your own custom ones  `Manage > Command Palette... > Snippets: Configure snippets... > r.json`

:::

## Data manipulation

Import packages to make data manipulation easier

::: {.panel-tabset group="lang"}

## R

```r
library(dplyr)
```

## Python

```python
import pandas as pd
```
:::

### Importing and exporting data
Read your data with an I/O (input/output) function.

::: {.panel-tabset group="lang"}

## R
```r
dataset <- read.csv("data/dataset.csv")
```

## Python

```python
df = pd.read_csv("data/dataset.csv")
```

:::

You can also export your data to a CSV file.

::: {.panel-tabset group="lang"}

## R

```r
write.csv(dataset, "data/output_name.csv")
```

## Python

```python
df.to_csv("data/output_name.csv")
```

:::

### Initial exploration
You'll want to explore the data to start with - below are a few functions to get started.

::: {.panel-tabset group="lang"}

## R

| Function | Example | Description |
| --- | --- | --- |
| `names()` | `names(dataset)` | Returns the variable names | 
| `str()` | `str(dataset)` | Returns the structure of the dataset (variable names, types and first entries) | 
| `$` | `dataset$variable` | Returns a specific variable |
| `unique()` | `unique(dataset$variable)` | Returns the unique values of a variable |
| `summary()` | `summary(dataset$variable)` | Returns a statistical summary of a variable |

## Python

| Function | Example | Description |
| --- | --- | --- |
| `df.columns` | | Returns the variable names | 
| `df.info()` | | Returns the structure of the dataset (variable names, counts and types) | 
| `df["variable"]` | | Returns a specific column |
| `df["variable"].unique()` | | Returns the unique values of a variable |
| `df.describe()` or `df["variable"].describe()` | Returns a statistical summary of the dataset or a variable |

:::

### Removing missing data

We can remove missing data by filtering the rows out.

::: {.panel-tabset group="lang"}

## R

```r
dataset <- dataset |>
  filter_out(is.na(variable_to_check_for_NAs))
```

Alternatively, the tidyr package (also from the Tidyverse) provides a function to drop rows with missing data:

```r
library(tidyr)
dataset <- dataset |>
  drop_na(variable_to_check_for_NAs)
```

See the [tidyr website](https://tidyr.tidyverse.org/) for more functions to deal with missing data.

## Python

```python
df = df[df["variable"].notna()]
```

:::

### Time series data
If you've picked a dataset with time-series data (e.g. a "date" variable), it might have been imported as a string, which is not very useful. You should transform that variable to the correct data type so that you can use it as a continuous variable.

::: {.panel-tabset group="lang"}

## R

Using a base R function, you can replace the column with the data converted to the correct type. For example, for a date:

```r
dataset$variable <- as.Date(dataset$variable)
```

The Tidyverse can make it easier with the lubridate package. For example, for a column that contains date as strings in the format "2026-12-31", you could use:

```r
library(lubridate)
dataset <- dataset |>
  mutate(variable = ymd(variable))
```

Having the right data type then allows to extract parts of the date (or date-time), to for example create per-year summaries:

```r
library(lubridate)
# extract the year into a new column
dataset <- dataset |>
  mutate(year = year(variable))
# use the year for a summary
dataset |>
  group_by(year) |>
  summarise(summary_variable = mean(variable_to_summarise))
```

See the [lubridate website](https://lubridate.tidyverse.org/) for more date-time parsing and extracting functions.

## Python

```python
df["variable"] = pd.to_datetime(df["variable"])
```

:::

### Categorical and ordered data
If you're dealing with categorical data, you can specify this explicitly to keep track of the levels.

::: {.panel-tabset group="lang"}

## R
```r
dataset$variable <- factor(dataset$variable)
```

## Python

```python
df["variable"] = df["variable"].astype("category")
```

:::

To manually specify the order of categories, 

::: {.panel-tabset group="lang"}

## R
Specify the order by sending in an ordered list of the levels joined with `c()`:

```r
dataset$variable <- factor(dataset$variable, levels = c("first_val", "second_val", ... ))
```

Alternatively, if you only need to specify the first (reference) level, use

```r
dataset$variable <- relevel(factor(dataset$variable), ref = "reference_level")
```

## Python

Use the `df["variable"].cat.reorder_categories()` function and use the `ordered = True` parameter,

```python
df["variable"] = df["variable"].cat.reorder_categories(["cat1", "cat2", ...], ordered = True)
```

If you're dealing with categorical data, look at the [pandas guide](https://pandas.pydata.org/docs/user_guide/categorical.html) for inspiration and help.
:::

:::{.callout-tip}
# Coffee survey

This is particularly useful for the **Coffee survey** dataset.
:::


### Renaming variables
Some datasets have cumbersome names for their variables which we can rename.

::: {.panel-tabset group="lang"}

## R

```r
df <- df %>% 
  rename(new_name = old_name)
```

## Python
Use `df.rename()`, sending a *dictionary* to the `columns = ` parameter:

```python
df = df.rename(columns = {"old_name": "new_name"})
```

:::{.callout-note}
# Dictionaries

A *dictionary* is a Python variable with key-value pairs. The structure is `key: value`, so above we have a dictionary with one key, `"old_name"` and corresponding value `"new_name"`. They are created as follows:

<i>
```python
example_dictionary = {"key1": "value1",
                      "key2": "value2",
                      "key3": "value3",
                      ...}
```
</i>

Note that multiple lines are used purely for readability, you could just as well do this on one line.
:::

:::

:::{.callout-tip}
# World population

This is particularly useful for the **World population** dataset.
:::


## Visualisation
We can make simple visualisations of our data.

::: {.panel-tabset group="lang"}

## R
Use `ggplot2`'s `ggplot()` function, with 

* `data = ` the dataset
* `mapping = ` the variables, provideed as an `aes(...)` object
* `geom_...` the geometries, e.g. `geom_line()`, `geom_point()` etc.

```r
library(ggplot2)

ggplot(data = dataset,
       mapping = aes(x = ..., y = ..., colour = ..., ...)) +
  geom_first_layer() + 
  geom_second_layer() + 
  ...
```

Take a look at the [ggplot2 documentation](https://ggplot2.tidyverse.org/) for more information.


**Plotly workaround**

If you're having issues using `ggplotly` (it's producing a blank plot), you can use this workaround to view it in your browser.

```r
plot <- ggplotly(saved_ggplot_image)
htmlwidgets::saveWidget(as_widget(plot), "plots/name_of_plot.html")
```

Opening that file will show you the image.

## Python
Use `seaborn`'s `relplot()`, `catplot()` and `displot()` functions. For example,

```python
import seaborn as sns

sns.relplot(data = df, x = "variable_x", y = "variable_y", hue = "variable_colour", ...)
```
:::

We can add additional customisations to our plots, such as axis labels.

::: {.panel-tabset group="lang"}

## R
Generally, `ggplot2` lets you do this with additional elements added to the plot. For example, to add axis labels,

```r
ggplot(data = dataset,
       mapping = aes(x = ..., y = ..., colour = ..., ...)) +
  geom_first_layer() + 
  geom_second_layer() + 
  labs(title = ..., var1 = ...)
```

## Python

The simplest way to do this in Python is to use the `matplotlib.pyplot` module's functions. Generally, this has the format `plt.<some_customisation>`. For example, to add axis labels,

```python
import seaborn as sns
import matplotlib.pyplot as plt

sns.relplot(data = df, x = "variable_x", y = "variable_y", hue = "variable_colour", ...)
plt.xlabel("x axis label")
plt.ylabel("y axis label")
```
:::